# Generated by Django 3.1.7 on 2021-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(default='ABC1234', max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('date', models.DateField(default=True)),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('toss_winner', models.CharField(max_length=20)),
                ('toss_decision', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('dl_applied', models.CharField(max_length=20)),
                ('winner', models.CharField(max_length=20)),
                ('win_by_runs', models.CharField(max_length=20)),
                ('win_by_wickets', models.CharField(max_length=20)),
                ('player_of_match', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=20)),
                ('umpire1', models.CharField(max_length=20)),
                ('umpire2', models.CharField(max_length=20)),
                ('umpire3', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Ipl',
        ),
    ]
